name: Remote deploy
run-name: ${{ github.actor }} is pushing updates to the remote server.
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.10.0'

      - name: Install client dependencies
        run: |
          cd client
          ls
          yarn install

      - name: Install server dependencies
        run: |
          cd server
          ls
          yarn install

      - name: Run tests
        run: |
          cd server
          yarn test
          

  Deploy-Changes:
    runs-on: ubuntu-latest
    needs: [Run-Tests]

    steps:
      - name: Compile & minify scripts
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: echo "hello world"
          # script: |
          #   cd full-mern-stack-app/server
          #   git pull
          #   ./deploy.sh
      
      - run: echo "Job completed - ${{ job.status }}."
